<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.documentElement.scrollHeight + 'px';
  }
</script>

<?php

echo "<h1> PHP Op-Cache GUI </h1>";
//require_once __DIR__ . '/../../../../vendor/amnuts/opcache-gui/index.php';

echo "<iframe src='" . $block->getGuiUrl() . "' title='react' style='height: 100%; width: 100%;' frameborder='0'  scrolling='no' onload='resizeIframe(this)'>";
