<style>
    .test-result {
    padding-bottom: 5px;
    font-size: 20px;
    color: greenyellow;
    background-color: black;
	}
    .test-error {
    color: red;
    font-size: 20px;
    font-weight: 600;
    }
</style>

<?php
//echo "<h1> PHP Op-Cache GUI </h1>";
echo '<h2>PHP Performance test </h2>';

function testPHP(){
$start = microtime(TRUE);
/* Start of the code to profile */ 
for ($a = 0; $a < 10000000; $a++) { $b = $a*$a; }
/* End of the code to profile */ 
$end = microtime(TRUE);
return $end - $start;
}
echo "<div class='test-result'> > The Test code snippet took " . testPHP() . " seconds to complete. </div>";
echo "<div class='test-result'> > The Test code snippet took " . testPHP() . " seconds to complete. </div>";
echo "<div class='test-result'> > The Test code snippet took " . testPHP() . " seconds to complete. </div>";

echo '<h2>PHP Opcahe test</h2>';

if(extension_loaded('Zend OPcache')){
	$free_memory = opcache_get_status(false)['memory_usage']['free_memory'];
	$validate_timestamps = opcache_get_configuration()['directives']['opcache.validate_timestamps'];
	if ($free_memory < 1000000){
    		echo "<div class='test-error'>Increase OpCache Memory - Not Enought Memory</div>";
	}
	if ($validate_timestamps === true){
    		echo "<div class='test-error'>Disable Timestamp Validation for production server</div>";
	}
} else {
	echo '<div  class="test-result">You do not have the Zend OPcache extension loaded. Opcache is not working </div>';
}
		
require_once __DIR__ . '/../../../../vendor/amnuts/opcache-gui/index.php';
